

const allBreeds = [
    {key: 'Affenpinscher', text: 'Affenpinscher', value: 'Affenpinscher'},
    {key: 'Afghan Hound', text: 'Afghan Hound', value: 'Afghan Hound'},
    {key: 'Airedale Terrier', text: 'Airedale Terrier', value: 'Airedale Terrier'},
    {key: 'Akita', text: 'Akita', value: 'Akita'},
    {key: 'Alaskan Malamute', text: 'Alaskan Malamute', value: 'Alaskan Malamute'},
    {key: 'Anatolian Shepherd Dog', text: 'Anatolian Shepherd Dog', value: 'Anatolian Shepherd Dog'},
    {key: 'Australian Cattle Dog', text: 'Australian Cattle Dog', value: 'Australian Cattle Dog'},
    {key: 'Australian Shepherd', text: 'Australian Shepherd', value: 'Australian Shepherd'},
    {key: 'Australian Silky Terrier', text: 'Australian Silky Terrier', value: 'Australian Silky Terrier'},
    {key: 'Australian Terrier', text: 'Australian Terrier', value: 'Australian Terrier'},
    {key: 'Azawakh', text: 'Azawakh', value: 'Azawakh'},
    {key: 'Barbet', text: 'Barbet', value: 'Barbet'},
    {key: 'Basenji', text: 'Basenji', value: 'Basenji'},
    {key: 'Basset Bleu De Gascogne', text: 'Basset Bleu De Gascogne', value: 'Basset Bleu De Gascogne'},
    {key: 'Basset Fauve De Bretagne', text: 'Basset Fauve De Bretagne', value: 'Basset Fauve De Bretagne'},
    {key: 'Basset Griffon Vendeen (Grand)', text: 'Basset Griffon Vendeen (Grand)', value: 'Basset Griffon Vendeen (Grand)'},
    {key: 'Basset Griffon Vendeen (Petit)', text: 'Basset Griffon Vendeen (Petit)', value: 'Basset Griffon Vendeen (Petit)'},
    {key: 'Basset Hound', text: 'Basset Hound', value: 'Basset Hound'},
    {key: 'Bavarian Mountain Hound', text: 'Bavarian Mountain Hound', value: 'Bavarian Mountain Hound'},
    {key: 'Beagle', text: 'Beagle', value: 'Beagle'},
    {key: 'Bearded Collie', text: 'Bearded Collie', value: 'Bearded Collie'},
    {key: 'Beauceron', text: 'Beauceron', value: 'Beauceron'},
    {key: 'Bedlington Terrier', text: 'Bedlington Terrier', value: 'Bedlington Terrier'},
    {key: 'Belgian Shepherd Dog (Groenendael)', text: 'Belgian Shepherd Dog (Groenendael)', value: 'Belgian Shepherd Dog (Groenendael)'},
    {key: 'Belgian Shepherd Dog (Laekenois)', text: 'Belgian Shepherd Dog (Laekenois)', value: 'Belgian Shepherd Dog (Laekenois)'},
    {key: 'Belgian Shepherd Dog (Malinois)', text: 'Belgian Shepherd Dog (Malinois)', value: 'Belgian Shepherd Dog (Malinois)'},
    {key: 'Belgian Shepherd Dog (Tervueren)', text: 'Belgian Shepherd Dog (Tervueren)', value: 'Belgian Shepherd Dog (Tervueren)'},
    {key: 'Bergamasco', text: 'Bergamasco', value: 'Bergamasco'},
    {key: 'Bernese Mountain Dog', text: 'Bernese Mountain Dog', value: 'Bernese Mountain Dog'},
    {key: 'Bichon Frise', text: 'Bichon Frise', value: 'Bichon Frise'},
    {key: 'Black & Tan Coonhound', text: 'Black & Tan Coonhound', value: 'Black & Tan Coonhound'},
    {key: 'Bloodhound', text: 'Bloodhound', value: 'Bloodhound'},
    {key: 'Bolognese', text: 'Bolognese', value: 'Bolognese'},
    {key: 'Border Collie', text: 'Border Collie', value: 'Border Collie'},
    {key: 'Border Terrier', text: 'Border Terrier', value: 'Border Terrier'},
    {key: 'Borzoi', text: 'Borzoi', value: 'Borzoi'},
    {key: 'Boston Terrier', text: 'Boston Terrier', value: 'Boston Terrier'},
    {key: 'Bouvier Des Flandres', text: 'Bouvier Des Flandres', value: 'Bouvier Des Flandres'},
    {key: 'Boxer', text: 'Boxer', value: 'Boxer'},
    {key: 'Bracco Italiano', text: 'Bracco Italiano', value: 'Bracco Italiano'},
    {key: 'Braque D’Auvergne', text: 'Braque D’Auvergne', value: 'Braque D’Auvergne'},
    {key: 'Briard', text: 'Briard', value: 'Briard'},
    {key: 'Brittany', text: 'Brittany', value: 'Brittany'},
    {key: 'Bull Terrier', text: 'Bull Terrier', value: 'Bull Terrier'},
    {key: 'Bull Terrier (Miniature)', text: 'Bull Terrier (Miniature)', value: 'Bull Terrier (Miniature)'},
    {key: 'Bulldog', text: 'Bulldog', value: 'Bulldog'},
    {key: 'Bullmastiff', text: 'Bullmastiff', value: 'Bullmastiff'},
    {key: 'Cairn Terrier', text: 'Cairn Terrier', value: 'Cairn Terrier'},
    {key: 'Canaan Dog', text: 'Canaan Dog', value: 'Canaan Dog'},
    {key: 'Canadian Eskimo Dog', text: 'Canadian Eskimo Dog', value: 'Canadian Eskimo Dog'},
    {key: 'Catalan Sheepdog', text: 'Catalan Sheepdog', value: 'Catalan Sheepdog'},
    {key: 'Cavalier King Charles Spaniel', text: 'Cavalier King Charles Spaniel', value: 'Cavalier King Charles Spaniel'},
    {key: 'Cesky Terrier', text: 'Cesky Terrier', value: 'Cesky Terrier'},
    {key: 'Chihuahua (Long Coat)', text: 'Chihuahua (Long Coat)', value: 'Chihuahua (Long Coat)'},
    {key: 'Chihuahua (Smooth Coat)', text: 'Chihuahua (Smooth Coat)', value: 'Chihuahua (Smooth Coat)'},
    {key: 'Chinese Crested', text: 'Chinese Crested', value: 'Chinese Crested'},
    {key: 'Chow Chow', text: 'Chow Chow', value: 'Chow Chow'},
    {key: 'Cirneco Dell Etna', text: 'Cirneco Dell Etna', value: 'Cirneco Dell Etna'},
    {key: 'Collie (Rough)', text: 'Collie (Rough)', value: 'Collie (Rough)'},
    {key: 'Collie (Smooth)', text: 'Collie (Smooth)', value: 'Collie (Smooth)'},
    {key: 'Coton De Tulear', text: 'Coton De Tulear', value: 'Coton De Tulear'},
    {key: 'Dachshund (Long Haired)', text: 'Dachshund (Long Haired)', value: 'Dachshund (Long Haired)'},
    {key: 'Dachshund (Miniature Long Haired)', text: 'Dachshund (Miniature Long Haired)', value: 'Dachshund (Miniature Long Haired)'},
    {key: 'Dachshund (Miniature Smooth Haired)', text: 'Dachshund (Miniature Smooth Haired)', value: 'Dachshund (Miniature Smooth Haired)'},
    {key: 'Dachshund (Miniature Wire Haired)', text: 'Dachshund (Miniature Wire Haired)', value: 'Dachshund (Miniature Wire Haired)'},
    {key: 'Dachshund (Smooth Haired)', text: 'Dachshund (Smooth Haired)', value: 'Dachshund (Smooth Haired)'},
    {key: 'Dachshund (Wire Haired)', text: 'Dachshund (Wire Haired)', value: 'Dachshund (Wire Haired)'},
    {key: 'Dalmatian', text: 'Dalmatian', value: 'Dalmatian'},
    {key: 'Dandie Dinmont Terrier', text: 'Dandie Dinmont Terrier', value: 'Dandie Dinmont Terrier'},
    {key: 'Deerhound', text: 'Deerhound', value: 'Deerhound'},
    {key: 'Dobermann', text: 'Dobermann', value: 'Dobermann'},
    {key: 'Dogue de Bordeaux', text: 'Dogue de Bordeaux', value: 'Dogue de Bordeaux'},
    {key: 'English Setter', text: 'English Setter', value: 'English Setter'},
    {key: 'English Toy Terrier (Black', text: 'English Toy Terrier (Black', value: 'English Toy Terrier (Black'},
    {key: 'Entlebucher Mountain Dog', text: 'Entlebucher Mountain Dog', value: 'Entlebucher Mountain Dog'},
    {key: 'Estrela Mountain Dog', text: 'Estrela Mountain Dog', value: 'Estrela Mountain Dog'},
    {key: 'Eurasier', text: 'Eurasier', value: 'Eurasier'},
    {key: 'Finnish Lapphund', text: 'Finnish Lapphund', value: 'Finnish Lapphund'},
    {key: 'Finnish Spitz', text: 'Finnish Spitz', value: 'Finnish Spitz'},
    {key: 'Fox Terrier (Smooth)', text: 'Fox Terrier (Smooth)', value: 'Fox Terrier (Smooth)'},
    {key: 'Fox Terrier (Wire)', text: 'Fox Terrier (Wire)', value: 'Fox Terrier (Wire)'},
    {key: 'Foxhound', text: 'Foxhound', value: 'Foxhound'},
    {key: 'French Bulldog', text: 'French Bulldog', value: 'French Bulldog'},
    {key: 'German Longhaired Pointer', text: 'German Longhaired Pointer', value: 'German Longhaired Pointer'},
    {key: 'German Pinscher', text: 'German Pinscher', value: 'German Pinscher'},
    {key: 'German Shepherd Dog', text: 'German Shepherd Dog', value: 'German Shepherd Dog'},
    {key: 'German Shorthaired Pointer', text: 'German Shorthaired Pointer', value: 'German Shorthaired Pointer'},
    {key: 'German Spitz (Klein)', text: 'German Spitz (Klein)', value: 'German Spitz (Klein)'},
    {key: 'German Spitz (Mittel)', text: 'German Spitz (Mittel)', value: 'German Spitz (Mittel)'},
    {key: 'German Wirehaired Pointer', text: 'German Wirehaired Pointer', value: 'German Wirehaired Pointer'},
    {key: 'Giant Schnauzer', text: 'Giant Schnauzer', value: 'Giant Schnauzer'},
    {key: 'Glen Of Imaal Terrier', text: 'Glen Of Imaal Terrier', value: 'Glen Of Imaal Terrier'},
    {key: 'Gordon Setter', text: 'Gordon Setter', value: 'Gordon Setter'},
    {key: 'Grand Bleu De Gascogne', text: 'Grand Bleu De Gascogne', value: 'Grand Bleu De Gascogne'},
    {key: 'Great Dane', text: 'Great Dane', value: 'Great Dane'},
    {key: 'Great Swiss Mountain Dog', text: 'Great Swiss Mountain Dog', value: 'Great Swiss Mountain Dog'},
    {key: 'Greenland Dog', text: 'Greenland Dog', value: 'Greenland Dog'},
    {key: 'Greyhound', text: 'Greyhound', value: 'Greyhound'},
    {key: 'Griffon Bruxellois', text: 'Griffon Bruxellois', value: 'Griffon Bruxellois'},
    {key: 'Griffon Fauve De Bretagne', text: 'Griffon Fauve De Bretagne', value: 'Griffon Fauve De Bretagne'},
    {key: 'Hamiltonstovare', text: 'Hamiltonstovare', value: 'Hamiltonstovare'},
    {key: 'Havanese', text: 'Havanese', value: 'Havanese'},
    {key: 'Hovawart', text: 'Hovawart', value: 'Hovawart'},
    {key: 'Hungarian Kuvasz', text: 'Hungarian Kuvasz', value: 'Hungarian Kuvasz'},
    {key: 'Hungarian Puli', text: 'Hungarian Puli', value: 'Hungarian Puli'},
    {key: 'Hungarian Pumi', text: 'Hungarian Pumi', value: 'Hungarian Pumi'},
    {key: 'Hungarian Vizsla', text: 'Hungarian Vizsla', value: 'Hungarian Vizsla'},
    {key: 'Hungarian Wire Haired Vizsla', text: 'Hungarian Wire Haired Vizsla', value: 'Hungarian Wire Haired Vizsla'},
    {key: 'Ibizan Hound', text: 'Ibizan Hound', value: 'Ibizan Hound'},
    {key: 'Irish Red & White', text: 'Irish Red & White', value: 'Irish Red & White'},
    {key: 'Irish Setter', text: 'Irish Setter', value: 'Irish Setter'},
    {key: 'Irish Terrier', text: 'Irish Terrier', value: 'Irish Terrier'},
    {key: 'Irish Wolfhound', text: 'Irish Wolfhound', value: 'Irish Wolfhound'},
    {key: 'Italian Greyhound', text: 'Italian Greyhound', value: 'Italian Greyhound'},
    {key: 'Italian Spinone', text: 'Italian Spinone', value: 'Italian Spinone'},
    {key: 'Jack Russell Terrier', text: 'Jack Russell Terrier', value: 'Jack Russell Terrier'},
    {key: 'Japanese Akita Inu', text: 'Japanese Akita Inu', value: 'Japanese Akita Inu'},
    {key: 'Japanese Chin', text: 'Japanese Chin', value: 'Japanese Chin'},
    {key: 'Japanese Shiba Inu', text: 'Japanese Shiba Inu', value: 'Japanese Shiba Inu'},
    {key: 'Japanese Spitz', text: 'Japanese Spitz', value: 'Japanese Spitz'},
    {key: 'Keeshond', text: 'Keeshond', value: 'Keeshond'},
    {key: 'Kerry Blue Terrier', text: 'Kerry Blue Terrier', value: 'Kerry Blue Terrier'},
    {key: 'King Charles Spaniel', text: 'King Charles Spaniel', value: 'King Charles Spaniel'},
    {key: 'Komondor', text: 'Komondor', value: 'Komondor'},
    {key: 'Kooikerhondje', text: 'Kooikerhondje', value: 'Kooikerhondje'},
    {key: 'Korean Jindo', text: 'Korean Jindo', value: 'Korean Jindo'},
    {key: 'Korthals Griffon', text: 'Korthals Griffon', value: 'Korthals Griffon'},
    {key: 'Lagotto Romagnolo', text: 'Lagotto Romagnolo', value: 'Lagotto Romagnolo'},
    {key: 'Lakeland Terrier', text: 'Lakeland Terrier', value: 'Lakeland Terrier'},
    {key: 'Lancashire Heeler', text: 'Lancashire Heeler', value: 'Lancashire Heeler'},
    {key: 'Large Munsterlander', text: 'Large Munsterlander', value: 'Large Munsterlander'},
    {key: 'Leonberger', text: 'Leonberger', value: 'Leonberger'},
    {key: 'Lhasa Apso', text: 'Lhasa Apso', value: 'Lhasa Apso'},
    {key: 'Lowchen (Little Lion Dog)', text: 'Lowchen (Little Lion Dog)', value: 'Lowchen (Little Lion Dog)'},
    {key: 'Maltese', text: 'Maltese', value: 'Maltese'},
    {key: 'Manchester Terrier', text: 'Manchester Terrier', value: 'Manchester Terrier'},
    {key: 'Maremma Sheepdog', text: 'Maremma Sheepdog', value: 'Maremma Sheepdog'},
    {key: 'Mastiff', text: 'Mastiff', value: 'Mastiff'},
    {key: 'Miniature Pinscher', text: 'Miniature Pinscher', value: 'Miniature Pinscher'},
    {key: 'Miniature Schnauzer', text: 'Miniature Schnauzer', value: 'Miniature Schnauzer'},
    {key: 'Neapolitan Mastiff', text: 'Neapolitan Mastiff', value: 'Neapolitan Mastiff'},
    {key: 'Newfoundland', text: 'Newfoundland', value: 'Newfoundland'},
    {key: 'Norfolk Terrier', text: 'Norfolk Terrier', value: 'Norfolk Terrier'},
    {key: 'Norwegian Buhund', text: 'Norwegian Buhund', value: 'Norwegian Buhund'},
    {key: 'Norwegian Elkhound', text: 'Norwegian Elkhound', value: 'Norwegian Elkhound'},
    {key: 'Norwich Terrier', text: 'Norwich Terrier', value: 'Norwich Terrier'},
    {key: 'Old English Sheepdog', text: 'Old English Sheepdog', value: 'Old English Sheepdog'},
    {key: 'Otterhound', text: 'Otterhound', value: 'Otterhound'},
    {key: 'Papillon', text: 'Papillon', value: 'Papillon'},
    {key: 'Parson Russell Terrier', text: 'Parson Russell Terrier', value: 'Parson Russell Terrier'},
    {key: 'Pekingese', text: 'Pekingese', value: 'Pekingese'},
    {key: 'Pharaoh Hound', text: 'Pharaoh Hound', value: 'Pharaoh Hound'},
    {key: 'Picardy Sheepdog', text: 'Picardy Sheepdog', value: 'Picardy Sheepdog'},
    {key: 'Pointer', text: 'Pointer', value: 'Pointer'},
    {key: 'Polish Lowland Sheepdog', text: 'Polish Lowland Sheepdog', value: 'Polish Lowland Sheepdog'},
    {key: 'Pomeranian', text: 'Pomeranian', value: 'Pomeranian'},
    {key: 'Poodle (Miniature)', text: 'Poodle (Miniature)', value: 'Poodle (Miniature)'},
    {key: 'Poodle (Standard)', text: 'Poodle (Standard)', value: 'Poodle (Standard)'},
    {key: 'Poodle (Toy)', text: 'Poodle (Toy)', value: 'Poodle (Toy)'},
    {key: 'Portuguese Podengo', text: 'Portuguese Podengo', value: 'Portuguese Podengo'},
    {key: 'Portuguese Pointer', text: 'Portuguese Pointer', value: 'Portuguese Pointer'},
    {key: 'Portuguese Water Dog', text: 'Portuguese Water Dog', value: 'Portuguese Water Dog'},
    {key: 'Pug', text: 'Pug', value: 'Pug'},
    {key: 'Pyrenean Mastiff', text: 'Pyrenean Mastiff', value: 'Pyrenean Mastiff'},
    {key: 'Pyrenean Mountain Dog', text: 'Pyrenean Mountain Dog', value: 'Pyrenean Mountain Dog'},
    {key: 'Pyrenean Sheepdog (Long Haired)', text: 'Pyrenean Sheepdog (Long Haired)', value: 'Pyrenean Sheepdog (Long Haired)'},
    {key: 'Retriever (Chesapeake Bay)', text: 'Retriever (Chesapeake Bay)', value: 'Retriever (Chesapeake Bay)'},
    {key: 'Retriever (Curly Coated)', text: 'Retriever (Curly Coated)', value: 'Retriever (Curly Coated)'},
    {key: 'Retriever (Flat Coated)', text: 'Retriever (Flat Coated)', value: 'Retriever (Flat Coated)'},
    {key: 'Retriever (Golden)', text: 'Retriever (Golden)', value: 'Retriever (Golden)'},
    {key: 'Retriever (Labrador)', text: 'Retriever (Labrador)', value: 'Retriever (Labrador)'},
    {key: 'Retriever (Nova Scotia Duck', text: 'Retriever (Nova Scotia Duck', value: 'Retriever (Nova Scotia Duck'},
    {key: 'Rhodesian Ridgeback', text: 'Rhodesian Ridgeback', value: 'Rhodesian Ridgeback'},
    {key: 'Rottweiler', text: 'Rottweiler', value: 'Rottweiler'},
    {key: 'Russian Black Terrier', text: 'Russian Black Terrier', value: 'Russian Black Terrier'},
    {key: 'Russian Toy', text: 'Russian Toy', value: 'Russian Toy'},
    {key: 'Saluki', text: 'Saluki', value: 'Saluki'},
    {key: 'Samoyed', text: 'Samoyed', value: 'Samoyed'},
    {key: 'Schipperke', text: 'Schipperke', value: 'Schipperke'},
    {key: 'Schnauzer', text: 'Schnauzer', value: 'Schnauzer'},
    {key: 'Scottish Terrier', text: 'Scottish Terrier', value: 'Scottish Terrier'},
    {key: 'Sealyham Terrier', text: 'Sealyham Terrier', value: 'Sealyham Terrier'},
    {key: 'Segugio Italiano', text: 'Segugio Italiano', value: 'Segugio Italiano'},
    {key: 'Shar Pei', text: 'Shar Pei', value: 'Shar Pei'},
    {key: 'Shetland Sheepdog', text: 'Shetland Sheepdog', value: 'Shetland Sheepdog'},
    {key: 'Shih Tzu', text: 'Shih Tzu', value: 'Shih Tzu'},
    {key: 'Siberian Husky', text: 'Siberian Husky', value: 'Siberian Husky'},
    {key: 'Skye Terrier', text: 'Skye Terrier', value: 'Skye Terrier'},
    {key: 'Sloughi', text: 'Sloughi', value: 'Sloughi'},
    {key: 'Slovakian Rough Haired Pointer', text: 'Slovakian Rough Haired Pointer', value: 'Slovakian Rough Haired Pointer'},
    {key: 'Small Munsterlander', text: 'Small Munsterlander', value: 'Small Munsterlander'},
    {key: 'Soft Coated Wheaten Terrier', text: 'Soft Coated Wheaten Terrier', value: 'Soft Coated Wheaten Terrier'},
    {key: 'Spaniel (American Cocker)', text: 'Spaniel (American Cocker)', value: 'Spaniel (American Cocker)'},
    {key: 'Spaniel (American Water)', text: 'Spaniel (American Water)', value: 'Spaniel (American Water)'},
    {key: 'Spaniel (Clumber)', text: 'Spaniel (Clumber)', value: 'Spaniel (Clumber)'},
    {key: 'Spaniel (Cocker)', text: 'Spaniel (Cocker)', value: 'Spaniel (Cocker)'},
    {key: 'Spaniel (English Springer)', text: 'Spaniel (English Springer)', value: 'Spaniel (English Springer)'},
    {key: 'Spaniel (Field)', text: 'Spaniel (Field)', value: 'Spaniel (Field)'},
    {key: 'Spaniel (Irish Water)', text: 'Spaniel (Irish Water)', value: 'Spaniel (Irish Water)'},
    {key: 'Spaniel (Sussex)', text: 'Spaniel (Sussex)', value: 'Spaniel (Sussex)'},
    {key: 'Spaniel (Welsh Springer)', text: 'Spaniel (Welsh Springer)', value: 'Spaniel (Welsh Springer)'},
    {key: 'Spanish Water Dog', text: 'Spanish Water Dog', value: 'Spanish Water Dog'},
    {key: 'St. Bernard', text: 'St. Bernard', value: 'St. Bernard'},
    {key: 'Staffordshire Bull Terrier', text: 'Staffordshire Bull Terrier', value: 'Staffordshire Bull Terrier'},
    {key: 'Swedish Lapphund', text: 'Swedish Lapphund', value: 'Swedish Lapphund'},
    {key: 'Swedish Vallhund', text: 'Swedish Vallhund', value: 'Swedish Vallhund'},
    {key: 'Tibetan Mastiff', text: 'Tibetan Mastiff', value: 'Tibetan Mastiff'},
    {key: 'Tibetan Spaniel', text: 'Tibetan Spaniel', value: 'Tibetan Spaniel'},
    {key: 'Tibetan Terrier', text: 'Tibetan Terrier', value: 'Tibetan Terrier'},
    {key: 'Turkish Kangal Dog', text: 'Turkish Kangal Dog', value: 'Turkish Kangal Dog'},
    {key: 'Weimaraner', text: 'Weimaraner', value: 'Weimaraner'},
    {key: 'Welsh Corgi (Cardigan)', text: 'Welsh Corgi (Cardigan)', value: 'Welsh Corgi (Cardigan)'},
    {key: 'Welsh Corgi (Pembroke)', text: 'Welsh Corgi (Pembroke)', value: 'Welsh Corgi (Pembroke)'},
    {key: 'Welsh Terrier', text: 'Welsh Terrier', value: 'Welsh Terrier'},
    {key: 'West Highland White Terrier', text: 'West Highland White Terrier', value: 'West Highland White Terrier'},
    {key: 'Whippet', text: 'Whippet', value: 'Whippet'},
    {key: 'White Swiss Shepherd Dog', text: 'White Swiss Shepherd Dog', value: 'White Swiss Shepherd Dog'},
    {key: 'Xoloitzcuintle (Mex Hairless) Int', text: 'Xoloitzcuintle (Mex Hairless) Int', value: 'Xoloitzcuintle (Mex Hairless) Int'},
    {key: 'Xoloitzcuintle (Mex Hairless) Min', text: 'Xoloitzcuintle (Mex Hairless) Min', value: 'Xoloitzcuintle (Mex Hairless) Min'},
    {key: 'Xoloitzcuintle (Mex Hairless) Std', text: 'Xoloitzcuintle (Mex Hairless) Std', value: 'Xoloitzcuintle (Mex Hairless) Std'},
    {key: 'Yorkshire Terrier', text: 'Yorkshire Terrier', value: 'Yorkshire Terrier'}
]

export default allBreeds